---
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 0
production:
  :concurrency: 12
:queues:
  - [decree-listers,   2]
  - [hearing-listers,  1]
  - [decree-crawlers,  2]
  - [hearing-crawlers, 1]
:limits:
  decree-listers:   2
  hearing-listers:  2
  decree-crawlers:  4
  hearing-crawlers: 4
